[package]
name = "kartapple-graphics-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

kart-apple-gl = "0.4.41"